Fix ShellCheck warnings

diff --git a/bin/src/general/shredall b/bin/src/general/shredall
--- a/bin/src/general/shredall
+++ b/bin/src/general/shredall
@@ -1,5 +1,5 @@
 #!/bin/bash
-PROGNAME=$(basename $0)
+PROG_NAME=$(basename "$0")
 
 quiet=false
 without_confirmation=false
@@ -111,7 +111,7 @@ function main() {
     fi
 
     if [ ! -e "$param" ]; then
-      echo -e "Shredded a file \""$param"\" successfully"
+      echo -e "Shredded a file \"$param\" successfully"
       exit 0
     fi
   fi
@@ -136,9 +136,9 @@ function confirm() {
     echo -en "Type file or directory name: "
 
     exec < /dev/tty
-    read confirm
+    read -r confirm
 
-    if [ $confirm = $(basename "$param") ]; then
+    if [ "$confirm" = "$(basename "$param")" ]; then
       echo -en ""
     else
       echo -e "canceled" >&2
@@ -151,26 +151,26 @@ function confirm() {
 
 function before_validate() {
   if [ "$param" = "" ]; then
-    echo "shredall: missing operand" >&2
+    echo "$PROG_NAME: missing operand" >&2
     exit 1
   fi
 
   if [ ! -e "$param" ]; then
-    echo "shredall: no such file or directory" >&2
+    echo "$PROG_NAME: no such file or directory" >&2
     exit 1
   fi
 
   if [[ "$(whoami)" != "root" ]]; then
-    echo "shredall: requires root privilege" >&2
-    echo "shredall: cannot shred write-protected files without root privilege" >&2
+    echo "$PROG_NAME: requires root privilege" >&2
+    echo "$PROG_NAME: cannot shred write-protected files without root privilege" >&2
     exit 1
   fi
 }
 
 function after_validate() {
-  ok_flag=`find "$param" -print | check`
+  ok_flag=$(find "$param" -print | check)
 
-  if [ $ok_flag = 0 ]; then
+  if [ "$ok_flag" = 0 ]; then
     # shred empty directories
     if $quiet; then
       rm -rf "$param"
@@ -181,17 +181,17 @@ function after_validate() {
     if [ ! -d "$param" ]; then
       echo -e "Shredded all files in \"$(realpath "$param")\" successfully"
     else
-      echo -e "Something went wrong! ("$param" even exists)" >&2
+      echo -e "Something went wrong! ($param even exists)" >&2
       exit 2
     fi
-  elif [ $ok_flag = 1 ]; then
-    find "$param" -print | while read dir; do
-      if [ ! -d $dir ]; then
-        echo -e "\nshredall: something went wrong: $dir is NOT a directory" >&2
+  elif [ "$ok_flag" = 1 ]; then
+    find "$param" -print | while read -r dir; do
+      if [ ! -d "$dir" ]; then
+        echo -e "\n$PROG_NAME: something went wrong: $dir is NOT a directory" >&2
       fi
     done
   else
-    echo -e "\nshredall: wrong flag" >&2
+    echo -e "\n$PROG_NAME: wrong flag" >&2
     exit 2
   fi
 }
@@ -199,7 +199,7 @@ function after_validate() {
 function check() {
   ok_flag=0
 
-  while read dir; do
+  while read -r dir; do
     if [ ! -d "$dir" ]; then
       ok_flag=1
     fi
@@ -231,11 +231,11 @@ function parse_options() {
         break
       ;;
       -* )
-        echo "$PROGNAME: illegal option -- '$(echo $1 | sed 's/^-*//')'" 1>&2
+        echo "$PROG_NAME: illegal option ${1//^-*/}" 1>&2
         exit 1
       ;;
       * )
-        if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
+        if [[ -n "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
           param+=( "$1" )
           shift 1
         fi
@@ -245,7 +245,7 @@ function parse_options() {
 }
 
 function usage() {
-  echo "$PROGNAME"
+  echo "$PROG_NAME"
   echo "	-h, --help"
   echo "		Show this message and exit"
   echo
