Throw error when no such file or directory

diff --git a/bin/src/general/shredall b/bin/src/general/shredall
--- a/bin/src/general/shredall
+++ b/bin/src/general/shredall
@@ -1,13 +1,18 @@
 #!/bin/bash
 
-if [[ "$(whoami)" != "root" ]]; then
-  echo "shredall: requires root privilege" >&2
-  echo "shredall: cannot shred write-protected files without root privilege" >&2
+if [ "$1" = "" ]; then
+  echo "shredall: missing operand" >&2
   exit 1
 fi
 
-if [ "$1" = "" ]; then
-  echo "shredall: missing operand" >&2
+if [ ! -e "$1" ]; then
+  echo "shredall: no such file or directory" >&2
+  exit 1
+fi
+
+if [[ "$(whoami)" != "root" ]]; then
+  echo "shredall: requires root privilege" >&2
+  echo "shredall: cannot shred write-protected files without root privilege" >&2
   exit 1
 fi
 
