Exit when no arguments given in git protect

diff --git a/bin/src/git_subcommand/git-protect b/bin/src/git_subcommand/git-protect
--- a/bin/src/git_subcommand/git-protect
+++ b/bin/src/git_subcommand/git-protect
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [[ "$#" = "0" ]]; then
+  echo -e "What branch do you want to protect?"
+  exit 1
+fi
+
 cat << EOL > $(git rev-parse --git-dir)/hooks/pre-push-before/protect
 #!/bin/bash
 
@@ -10,7 +15,7 @@ EOL
 cat << 'EOL' >> $(git rev-parse --git-dir)/hooks/pre-push-before/protect
 for pb in ${protected_branches[@]}; do
   if [[ "${remote_ref##refs/heads/}" = "$pb" ]]; then
-    echo -e "\033[1;91merror: to push into $pb branch is prohibited\033[00m"
+    echo -e "\033[1;91mERROR: To push into $pb branch is prohibited\033[00m"
     exit 1
   fi
 done
